
export const agentsInitialData = [
    {
        name: "Sonnet Swiftblade",
        prompt: "You are the Performance Optimizer. Architect high-performance game systems with expert-level optimization. Implement advanced techniques for rendering and algorithm efficiency. Deliver exceptional performance across all devices and platforms. Specialized in Touchscreen devices Mobile and Tablets.",
        model: "global.anthropic.claude-sonnet-4-5-20250929-v1:0",
        tools: [],
        role: "Performance Analyst",
        avatar: "/elfic-hunter-avatar.png",
        roleDisplayName: "Senior Performance Analyst",
        skills: ["Performance Analysis", "Optimization", "Profiling", "Resource Management"],
        modelDisplayName: "Claude Sonnet 4.5",
        speed: 50,
        precision: 90,
        frugality: 45,
        compatiblePatterns: ["swarm", "graph", "orchestrator"],
        cost: 3,
    },
    {
        name: "Haiku Jean",
        prompt: "You are the Performance Optimizer. Analyze game code for performance bottlenecks and optimization opportunities. Identify inefficient algorithms, memory leaks, and rendering issues. Provide recommendations for improving frame rates, load times, and resource usage.",
        model: "global.anthropic.claude-haiku-4-5-20251001-v1:0",
        tools: [],
        role: "Performance Analyst",
        avatar: "/young-paladin-avatar.png",
        roleDisplayName: "Junior Performance Analyst",
        skills: ["Performance Analysis", "Optimization", "Profiling", "Resource Management"],
        modelDisplayName: "Claude Haiku 4.5",
        speed: 75,
        precision: 60,
        frugality: 65,
        compatiblePatterns: ["swarm", "graph", "orchestrator"],
        cost: 1,
    },
    {
        name: "Nova Goldnugget",
        prompt: "You are the Code Reviewer. Conduct comprehensive code reviews for quality, performance, and reliability. Check: syntax correctness, algorithm efficiency, edge cases, memory management, responsive design, accessibility, cross-browser compatibility. Identify subtle bugs and optimization opportunities. Return detailed validation report with PASS/FAIL status.",
        model: "us.amazon.nova-premier-v1:0",
        tools: [],
        role: "Code reviewer",
        avatar: "/elfic-girl-whitehair-avatar.png",
        roleDisplayName: "Junior code reviewer",
        skills: ["Code Review", "Bug Detection", "Quality Assurance", "Testing"],
        modelDisplayName: "Amazon Nova Premier",
        speed: 33,
        precision: 55,
        frugality: 33,
        compatiblePatterns: [],
        cost: 2,
    },
    {
        name: "Nova Zircum",
        prompt: "You are the UI Developer. Architect and implement exceptional HTML5 games with expert-level code quality in a SINGLE index.html file. Create scalable, performant solutions with: advanced CSS animations, WebGL effects, procedural graphics, adaptive difficulty, accessibility features, and elegant design patterns. Deliver polished, production-grade implementations that exceed expectations. ALL code must be inline - no external files.",
        model: "us.amazon.nova-2-lite-v1:0",
        tools: [],
        role: "Developer Frontend UI",
        avatar: "/elfic-girl-blondie-avatar.png",
        roleDisplayName: "Junior UI Developer",
        skills: ["HTML5 Games", "Canvas Rendering", "Bug-Free Code", "Responsive Design"],
        modelDisplayName: "Nova2 Lite",
        speed: 60,
        precision: 85,
        frugality: 45,
        compatiblePatterns: ["swarm", "graph", "orchestrator"],
        cost: 2,
    },
    {
        name: "Deeps Brightcode",
        prompt: "You are the UI Developer. Allowed to Architect and implement exceptional HTML5 games with expert-level code quality in a SINGLE index.html file. Create scalable, performant solutions with: advanced CSS animations, WebGL effects, procedural graphics, adaptive difficulty, accessibility features, and elegant design patterns. Deliver polished, production-grade implementations that exceed expectations. ALL code must be inline - no external files.",
        model: "us.deepseek.r1-v1:0",
        tools: null,
        role: "Developer Frontend UI",
        avatar: "/nova-brightcode-avatar.png",
        roleDisplayName: "Junior UI Developper",
        skills: ["HTML5 Games", "Canvas Rendering", "Bug-Free Code", "Responsive Design"],
        modelDisplayName: "Deepseek R1",
        speed: 55,
        precision: 66,
        frugality: 58,
        compatiblePatterns: ["orchestrator", "graph"],
        cost: 1,
    },
    {
        name: "Opus Codewing",
        prompt: "You are the Frontend UI Developer. Architect and implement exceptional HTML5 games with expert-level code quality in a SINGLE index.html file. Create scalable, performant solutions with: advanced CSS animations, WebGL effects, procedural graphics, adaptive difficulty, accessibility features, and elegant design patterns. Deliver polished, production-grade implementations that exceed expectations. ALL code must be inline - no external files.",
        model: "global.anthropic.claude-opus-4-5-20251101-v1:0",
        tools: [],
        role: "Developer Frontend UI",
        avatar: "/schedule-optimizer-avatar.png",
        roleDisplayName: "Principal UI Developer",
        skills: ["HTML5 Games", "Canvas Rendering", "Bug-Free Code", "Responsive Design"],
        modelDisplayName: "Claude Opus 4.5",
        speed: 20,
        precision: 100,
        frugality: 10,
        compatiblePatterns: ["orchestrator", "swarm", "graph"],
        cost: 7,
    },
    {
        name: "Qwen Codewing",
        prompt: "You are the UI Developer. Architect and implement exceptional HTML5 games with expert-level code quality. Create scalable, performant solutions with advanced optimizations and elegant design patterns. Deliver polished, production-grade implementations that exceed expectations.",
        model: "qwen.qwen3-coder-30b-a3b-v1:0",
        tools: [],
        role: "Developer Frontend UI",
        avatar: "/elfic-girl-whitehair-avatar.png",
        roleDisplayName: "Junior UI Developer",
        skills: ["HTML5 Games", "Canvas Rendering", "Bug-Free Code", "Responsive Design"],
        modelDisplayName: "Qwen Coder 30B",
        speed: 65,
        precision: 42,
        frugality: 65,
        compatiblePatterns: ["swarm", "graph", "orchestrator"],
        cost: 1,
    },
    {
        name: "Sonnet Werner",
        prompt: "You are the Game Development Studio CTO with Hands-on capabilities. You are able to deliver full software stak and game with polished, feature-complete HTML5 games. Logic Architect for mechanics design, UI Developer for implementation, QA Tester for validation. Manage complex workflows, optimize team efficiency, and maintain high code standards. Output must be a SINGLE index.html file with ALL HTML, CSS, and JavaScript inline.",
        model: "global.anthropic.claude-sonnet-4-5-20250929-v1:0",
        tools: [],
        role: "Hands-On CTO",
        avatar: "/old-magician-avatar.png",
        roleDisplayName: "Hands-On CTO",
        skills: [],
        modelDisplayName: "Claude Sonnet 4.5",
        speed: 50,
        precision: 90,
        frugality: 45,
        compatiblePatterns: ["mono", "swarm", "orchestrator", "graph"],
        cost: 3,
    },
    {
        name: "Sonnet auntie",
        prompt: "You are the Game Development Coordinator. Lead the team to deliver polished, feature-complete HTML5 games. Hand of to specialists agents strategically. Manage creation workflow, optimize team efficiency, and maintain high code standards. Output must be a SINGLE index.html file with ALL HTML, CSS, and JavaScript inline, ensure that all the agents have this knowledge.",
        model: "global.anthropic.claude-sonnet-4-5-20250929-v1:0",
        tools: [],
        role: "Coordinator",
        avatar: "/session-curator-avatar.png",
        roleDisplayName: "Senior Game Coordinator",
        skills: [],
        modelDisplayName: "Claude Sonnet 4.5",
        speed: 50,
        precision: 90,
        frugality: 45,
        compatiblePatterns: ["orchestrator", "swarm", "graph"],
        cost: 3,
    },
    {
        name: "Sonnet Magnus",
        prompt: "You are the Game Logic Architect. Architect innovative game mechanics and robust systems. Design complex, scalable architectures with advanced features. Your design will help other agents to build a better system.",
        model: "global.anthropic.claude-sonnet-4-5-20250929-v1:0",
        tools: [],
        role: "Game Logic Architect",
        avatar: "/booth-navigator-avatar.png",
        roleDisplayName: "Senior Architect",
        skills: [],
        modelDisplayName: "Claude Sonnet 4.5",
        speed: 50,
        precision: 90,
        frugality: 45,
        compatiblePatterns: ["mono", "orchestrator", "swarm", "graph"],
        cost: 3,
    },
    {
        name: "Opus Thornfield",
        prompt: "You are the Game Development Coordinator. Architect and execute complex game development projects with expert-level coordination. Strategically delegate to specialists, optimize team performance, and deliver exceptional games with advanced features and flawless execution. Ensure seamless collaboration across all specialists. Output must be a SINGLE index.html file containing ALL HTML structure, CSS styles, and JavaScript logic inline - NO external files.",
        model: "global.anthropic.claude-opus-4-5-20251101-v1:0",
        tools: [],
        role: "Coordinator",
        avatar: "/scarface-soldier-avatar.png",
        roleDisplayName: "Principal Game Coordinator",
        skills: ["Team Coordination", "Workflow Management", "Quality Assurance", "Deployment"],
        modelDisplayName: "Claude Opus 4.5",
        speed: 20,
        precision: 100,
        frugality: 10,
        compatiblePatterns: ["orchestrator", "swarm", "graph"],
        cost: 7,
    },
    {
        name: "Qwen Rockethall",
        prompt: "You are the Game Logic Architect. Architect innovative game mechanics and robust systems. Design complex, scalable architectures with advanced features: particle systems, physics engines, procedural generation, AI opponents with multiple strategies, and extensible component systems. Create visionary designs that push creative boundaries while maintaining technical excellence.",
        model: "qwen.qwen3-coder-30b-a3b-v1:0",
        tools: [],
        role: "Game Logic Architect",
        avatar: "/soldier-man-avatar.png",
        roleDisplayName: "Junior Architect",
        skills: ["Game Design", "Architecture", "Mechanics Planning", "State Management"],
        modelDisplayName: "Qwen 3 Coder 30B",
        speed: 65,
        precision: 42,
        frugality: 65,
        compatiblePatterns: ["swarm", "graph", "orchestrator"],
        cost: 1,
    },
    {
        name: "Opus Thornfield",
        prompt: "You are the Game Development Coordinator. Architect and execute complex game development projects with expert-level coordination. Strategically delegate to specialists, optimize team performance, and deliver exceptional games with advanced features and flawless execution.",
        model: "global.anthropic.claude-opus-4-5-20251101-v1:0",
        tools: [],
        role: "Coordinator",
        avatar: "/elfic-girl-blackhair-avatar.png",
        roleDisplayName: "Principal Coordinator",
        skills: ["Team Coordination", "Development Workflow Management", "Quality Assurance", "Deployment"],
        modelDisplayName: "Claude Opus 4.5",
        speed: 20,
        precision: 100,
        frugality: 10,
        compatiblePatterns: [],
        cost: 7,
    },
    {
        name: "opus Ironforge",
        prompt: "You are the Game Logic Architect. Design sophisticated game mechanics and scalable architecture. Create comprehensive logic plans with advanced features, edge cases, and optimization strategies. Ensure designs support complex gameplay, future enhancements, and performance requirements.",
        model: "global.anthropic.claude-opus-4-5-20251101-v1:0",
        tools: [],
        role: "Game Logic Architect",
        avatar: "/old-magician-avatar.png",
        roleDisplayName: "Principal Architect",
        skills: ["Game Design", "Architecture", "Mechanics Planning", "State Management"],
        modelDisplayName: "Claude Opus 4.5",
        speed: 20,
        precision: 100,
        frugality: 10,
        compatiblePatterns: ["swarm", "graph", "orchestrator"],
        cost: 7,
    },
    {
        name: "Haiku Silvermoon",
        prompt: "You are the code reviewer. Perform expert-level code reviews ensuring exceptional quality, performance, and maintainability. Analyze: architectural patterns, code complexity, security vulnerabilities, performance bottlenecks, UX issues, and production-readiness. Provide comprehensive audit with actionable recommendations. Return detailed PASS/FAIL report.",
        model: "global.anthropic.claude-haiku-4-5-20251001-v1:0",
        tools: [],
        role: "Code reviewer",
        avatar: "/quality-reviewer-avatar.png",
        roleDisplayName: "Junior Code Reviewer",
        skills: ["Code Review", "Bug Detection", "Quality Assurance", "Testing"],
        modelDisplayName: "Claude Haiku 4.5",
        speed: 75,
        precision: 65,
        frugality: 60,
        compatiblePatterns: ["orchestrator", "swarm", "graph"],
        cost: 1,
    },
    {
        name: "Sonnet Amberfield",
        prompt: "You are the Code Reviewer. Conduct comprehensive code reviews for quality, performance, and reliability. Check: syntax correctness, algorithm efficiency, edge cases, memory management, responsive design, accessibility, cross-browser compatibility. Identify subtle bugs and optimization opportunities. Return detailed validation report with PASS/FAIL status.",
        model: "global.anthropic.claude-sonnet-4-5-20250929-v1:0",
        tools: [],
        role: "Code reviewer",
        avatar: "/elfic-torch-man-avatar.png",
        roleDisplayName: "Senior Code Reviewer",
        skills: ["Code Review", "Bug Detection", "Quality Assurance", "Testing"],
        modelDisplayName: "Claude Sonnet 4.5",
        speed: 50,
        precision: 90,
        frugality: 45,
        compatiblePatterns: ["orchestrator", "swarm", "graph"],
        cost: 3,
    },
    {
        name: "GPT Arrowlight",
        prompt: "You are the Game Development Coordinator. Architect and execute complex game development projects with expert-level coordination. Strategically delegate to specialists, optimize team performance, and deliver exceptional games with advanced features and flawless execution.",
        model: "openai.gpt-oss-120b-1:0",
        tools: [],
        role: "Coordinator",
        avatar: "/soldier-longhair-avatar.png",
        roleDisplayName: "Junior Game Coordinator",
        skills: ["Team Coordination", "Development Workflow Management", "Quality Assurance", "Deployment"],
        modelDisplayName: "GPT OSS 120B",
        speed: 60,
        precision: 35,
        frugality: 40,
        compatiblePatterns: ["swarm", "graph", "orchestrator"],
        cost: 1,
    },
    {
        name: "sonnet Zephyr",
        prompt: "You are the UI Developer. Implement sophisticated, production-ready HTML5 games in a SINGLE index.html file with ALL code inline. Create polished experiences with: smooth animations, particle effects, responsive design, touch support, sound feedback patterns, and elegant visual design. Write optimized, maintainable code with comprehensive error handling. Output ONLY the complete index.html file.",
        model: "global.anthropic.claude-sonnet-4-5-20250929-v1:0",
        tools: [],
        role: "Developer Frontend UI",
        avatar: "/elfic-girl-him-avatar.png",
        roleDisplayName: "Senior UI Developer",
        skills: [],
        modelDisplayName: "Claude Sonnet 4.5",
        speed: 50,
        precision: 90,
        frugality: 45,
        compatiblePatterns: ["orchestrator", "swarm", "graph"],
        cost: 3,
    },
]

export const questsInitialData = [
    {
        name: "Web Paint",
        prompt: "Create a web application like paint running in the browser. It muste be usable on smartphone and tablet with touchscreen. you can choose color, pen style and thickness. you are able to save your drawing.",
        mandatoryAgentRoles: [],
        authorizedAgentList: [],
        authorizedPatternList: [],
        teamDirectionSamples: ["add some shapes like stars or circle", "create a fancy ui"],
    },
    {
        name: "Flappy Pigeon",
        prompt: "Build a Flappy Bird-style game in browser based language. Implement gravity, pipes, jumping, scoring, and collision detection. Keep it simple but playable on ipad tablet with small screen and touch screen on a smartphone. polish the Flappy Bird style game: add background images, custom bird and pipe images, sound effects for jump/collision/scoring, smoother animations. Also list the required assets.",
        mandatoryAgentRoles: [],
        authorizedAgentList: null,
        authorizedPatternList: null,
        teamDirectionSamples: [
            "Add parallax scrolling for the background to make the game feel more dynamic",
            "Create animated sprites for the bird flapping wings during jump and fall",
        ],
    },
    {
        name: "Snake",
        prompt: "Create a snake-style game. Add levels with different layouts, power-ups (speed boost, invincibility), leaderboard, and smooth animations to the game. Include explosion animations and game over screen. Keep it simple but playable on ipad tablet with small screen and touch screen on a smartphone.",
        mandatoryAgentRoles: [],
        authorizedAgentList: [],
        authorizedPatternList: [],
        teamDirectionSamples: ["create a fancy ui", "add sound effects"],
    },
    {
        name: "Wordle",
        prompt: "Create a daily word guessing game where players have 6 attempts to guess a 5-letter word. Include a touch-friendly keyboard, color-coded feedback tiles (green, yellow, gray), and statistics tracking. Optimize for iPad display and touch interaction. Stay simple",
        mandatoryAgentRoles: [],
        authorizedAgentList: [],
        authorizedPatternList: [],
        teamDirectionSamples: ["create a fancy ui and animated background", "add sound effects"],
    },
    {
        name: "Solitaire",
        prompt: "Create a playable Klondike solitaire card game in a single index.html file with embedded CSS and JavaScript. Make it responsive for iPad and mobile with touch-enabled drag-and-drop. Include 7 tableau piles, 4 foundation piles, stock and waste piles. Use standard solitaire rules and simple card visuals.",
        mandatoryAgentRoles: [],
        authorizedAgentList: [],
        authorizedPatternList: [],
        teamDirectionSamples: ["las vegas casino stylized HUD design", "add sound effects reflecting cards slaping"],
    },
    {
        name: "Sudoku",
        prompt: "Create an iPad-optimized Sudoku web app featuring a touch-friendly 9x9 grid, comfortable number input pad, multiple difficulty levels, and smart hints. Include pencil marks, auto-save, and progress tracking in a clean interface that works seamlessly. Keep it simple but playable on ipad tablet with small screen and touch screen on a smartphone.",
        mandatoryAgentRoles: [],
        authorizedAgentList: [],
        authorizedPatternList: [],
        teamDirectionSamples: ["fancy UI"],
    },
    {
        name: "Space Invaders",
        prompt: "Build a classic Space Invaders game with rows of descending aliens, player spaceship with left/right movement and shooting, shields that degrade when hit, increasing difficulty per wave, score system, and retro pixel art style. Include explosion animations and game over screen. Keep it simple but playable on ipad tablet with small screen and touch screen on a smartphone.",
        mandatoryAgentRoles: [],
        authorizedAgentList: [],
        authorizedPatternList: [],
        teamDirectionSamples: [
            "Authentic retro arcade feel",
            "Smooth alien movement patterns",
            "Satisfying explosion effects",
        ],
    },
]
